services:

  my-postgres:
    image: postgres:16
    container_name: my-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todo_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - todo-net

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:postgres@my-postgres:5432/todo_db
    depends_on:
      my-postgres:
        condition: service_healthy
    networks:
      - todo-net

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - todo-net

volumes:
  pgdata: 

networks:
  todo-net: