# Create docker images and scan it

name: Docker Build and Scan

on:
  workflow_dispatch:

jobs:
  docker-build-scan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        folders: ["frontend", "backend"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: ${{matrix.folders}} Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{matrix.folders}}/Dockerfile

      - name: ${{matrix.folders}} Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./${{matrix.folders}}
          file: ./${{matrix.folders}}/Dockerfile
          load: true
          tags: todo-${{matrix.folders}}:${{github.sha}}

      - name: ${{matrix.folders}} Scan Docker image
        uses: aquasecurity/trivy-action@v2
        with:
          image-ref: todo-${{matrix.folders}}:${{github.sha}}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'
          
          