name: Secrets Scan

on:
  workflow_dispatch:  

jobs:
  secret-scanning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for secret scanning

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog-enterprise-action@main
        with:
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified